name: David Swan
favicon: null
layout_spectrum: 0.7694988651201129
typography_spectrum: 0.8371766379568726
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.4492097902111709
  lightness: 0.36926784669049084
  saturation: 0.9299925756640732
  rhythmicContrast: 0.5944156874902546
purpose: []
